
const API_URL = "https://script.google.com/macros/s/AKfycbwffzjetYEb8UzLJb2MAsGFKCWCNWGbccDubDdE2xNTuDk-unHNishI_75NiHnIwooF_A/exec";
const NO_IMAGE_HTML = `<div class="no-image-visual"><div><svg viewBox="0 0 160 160" aria-hidden="true"><path d="M52 35c3-17 19-28 34-22 10 4 16 13 17 24" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round"/><path d="M80 55 30 96c-6 5-3 15 5 15h90c8 0 11-10 5-15L80 55Z" fill="none" stroke="currentColor" stroke-width="7" stroke-linejoin="round"/><path d="M80 55V43" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round"/></svg><strong>NO IMAGE</strong><small>写真を準備中です</small></div></div>`;

const state={items:[],filtered:[],selected:new Set()};
const q=s=>document.querySelector(s);
const els={grid:q("#catalogGrid"),status:q("#status"),count:q("#resultCount"),search:q("#searchInput"),category:q("#categoryFilter"),color:q("#colorFilter"),sleeve:q("#sleeveFilter"),pattern:q("#patternFilter"),reset:q("#resetButton"),template:q("#cardTemplate"),itemDialog:q("#itemDialog"),dialogContent:q("#dialogContent"),tray:q("#selectionTray"),selectionCount:q("#selectionCount"),viewSelection:q("#viewSelectionButton"),selectionDialog:q("#selectionDialog"),selectionList:q("#selectionList"),copy:q("#copySelectionButton"),clear:q("#clearSelectionButton"),copyMessage:q("#copyMessage")};

const field=(item,names)=>{for(const n of names){if(item[n]!==undefined&&item[n]!==null&&String(item[n]).trim()!=="")return String(item[n]).trim()}return""};
const itemId=(item,i)=>field(item,["ID","Id","id"])||`item-${i}`;
const itemName=item=>field(item,["サブカテゴリ","商品名","アイテム名","名称"])||field(item,["カテゴリ"])||"衣装";

function driveImageUrl(url){if(!url)return"";const t=String(url).trim();let m=t.match(/\/file\/d\/([a-zA-Z0-9_-]+)/)||t.match(/[?&]id=([a-zA-Z0-9_-]+)/);return m?`https://drive.google.com/thumbnail?id=${m[1]}&sz=w1200`:t}
function imageUrls(item){return[
 field(item,["写真1","画像1","着用画像1","着用写真1","着用画像","着用写真"]),
 field(item,["写真2","画像2","着用画像2","着用写真2","ハンガー画像"]),
 field(item,["写真3","画像3","着用画像3","着用写真3"])
].map(driveImageUrl)}
function imageUrl(item){return imageUrls(item).find(Boolean)||""}

function unique(names){return[...new Set(state.items.map(i=>field(i,names)).filter(Boolean).flatMap(v=>v.split(/[、,／/]/).map(x=>x.trim())).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ja"))}
function fill(select,values){values.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;select.append(o)})}
function setupFilters(){fill(els.category,unique(["カテゴリ"]));fill(els.color,unique(["色","カラー"]));fill(els.sleeve,unique(["袖丈","袖"]));fill(els.pattern,unique(["柄"]))}
function includesValue(actual,selected){if(!selected)return true;return actual.split(/[、,／/]/).map(v=>v.trim()).includes(selected)}
function applyFilters(){const query=els.search.value.trim().toLowerCase();state.filtered=state.items.filter(item=>{const searchable=Object.entries(item).filter(([k])=>!["ブランド","サイズ"].includes(k)).map(([,v])=>v).join(" ").toLowerCase();return(!query||searchable.includes(query))&&includesValue(field(item,["カテゴリ"]),els.category.value)&&includesValue(field(item,["色","カラー"]),els.color.value)&&includesValue(field(item,["袖丈","袖"]),els.sleeve.value)&&includesValue(field(item,["柄"]),els.pattern.value)});render()}

function render(){els.grid.replaceChildren();els.status.textContent="";els.count.textContent=`${state.filtered.length} ITEMS`;if(!state.filtered.length){els.status.textContent="条件に合う衣装がありません。";return}state.filtered.forEach(item=>{const i=state.items.indexOf(item),id=itemId(item,i),f=els.template.content.cloneNode(true),card=f.querySelector(".card"),img=f.querySelector(".card__image"),ph=f.querySelector(".card__placeholder"),select=f.querySelector(".select-button"),url=imageUrl(item);ph.innerHTML=NO_IMAGE_HTML;f.querySelector(".card__meta").textContent=field(item,["カテゴリ"]);f.querySelector(".card__title").textContent=itemName(item);f.querySelector(".card__tags").textContent=[field(item,["色"]),field(item,["柄"]),field(item,["袖丈"])].filter(Boolean).join(" ・ ");if(url){img.src=url;img.alt=itemName(item);img.addEventListener("error",()=>card.classList.add("no-image"))}else card.classList.add("no-image");f.querySelector(".card__image-button").addEventListener("click",()=>openItem(item,id));updateSelect(select,id);select.addEventListener("click",()=>toggle(id));els.grid.append(f)})}
function updateSelect(btn,id){const on=state.selected.has(id);btn.classList.toggle("is-selected",on);btn.textContent=on?"選択済み":"選択する"}
function toggle(id){state.selected.has(id)?state.selected.delete(id):state.selected.add(id);updateTray();render()}
function updateTray(){els.selectionCount.textContent=state.selected.size;els.tray.classList.toggle("is-visible",state.selected.size>0)}

function openItem(item,id){const details=[["カテゴリ",field(item,["カテゴリ"])],["色",field(item,["色"])],["柄",field(item,["柄"])],["袖丈",field(item,["袖丈","袖"])],["季節",field(item,["季節"])],["テイスト",field(item,["テイスト"])],["素材",field(item,["素材"])]].filter(([,v])=>v);const urls=imageUrls(item);const slides=urls.map((u,n)=>`<div class="photo-gallery__slide">${u?`<img src="${u}" alt="${itemName(item)}の写真${n+1}">`:NO_IMAGE_HTML}</div>`).join("");els.dialogContent.innerHTML=`<div class="item-detail"><div class="photo-gallery"><button class="photo-gallery__arrow photo-gallery__arrow--prev" type="button" aria-label="前の写真">‹</button><div class="photo-gallery__track">${slides}</div><button class="photo-gallery__arrow photo-gallery__arrow--next" type="button" aria-label="次の写真">›</button><div class="photo-gallery__dots">${urls.map((_,i)=>`<span class="photo-gallery__dot${i===0?" is-active":""}"></span>`).join("")}</div></div><div class="item-detail__content"><p class="section-kicker">ITEM DETAIL</p><h2>${itemName(item)}</h2><dl class="detail-list">${details.map(([l,v])=>`<div><dt>${l}</dt><dd>${v}</dd></div>`).join("")}</dl>${field(item,["メモ"])?`<p>${field(item,["メモ"])}</p>`:""}<button id="dialogSelectButton" class="primary-button">${state.selected.has(id)?"選択を解除":"この衣装を選ぶ"}</button></div></div>`;const track=els.dialogContent.querySelector(".photo-gallery__track"),dots=[...els.dialogContent.querySelectorAll(".photo-gallery__dot")],prev=els.dialogContent.querySelector(".photo-gallery__arrow--prev"),next=els.dialogContent.querySelector(".photo-gallery__arrow--next");const move=direction=>track.scrollBy({left:direction*track.clientWidth,behavior:"smooth"});prev.addEventListener("click",()=>move(-1));next.addEventListener("click",()=>move(1));track.addEventListener("scroll",()=>requestAnimationFrame(()=>{const i=Math.round(track.scrollLeft/Math.max(track.clientWidth,1));dots.forEach((d,n)=>d.classList.toggle("is-active",i===n));prev.disabled=i<=0;next.disabled=i>=dots.length-1}),{passive:true});prev.disabled=true;els.dialogContent.querySelectorAll("img").forEach(img=>img.addEventListener("error",()=>img.parentElement.innerHTML=NO_IMAGE_HTML));q("#dialogSelectButton").addEventListener("click",()=>{toggle(id);els.itemDialog.close()});els.itemDialog.showModal()}

function selectedItems(){return state.items.filter((item,i)=>state.selected.has(itemId(item,i)))}
function showSelection(){els.selectionList.replaceChildren();selectedItems().forEach(item=>{const row=document.createElement("div"),url=imageUrl(item),id=itemId(item,state.items.indexOf(item));row.className="selection-item";row.innerHTML=`${url?`<img src="${url}" alt="">`:`<div>${NO_IMAGE_HTML}</div>`}<div><h3>${itemName(item)}</h3><p>${[field(item,["カテゴリ"]),field(item,["色"])].filter(Boolean).join(" / ")}</p></div><button>解除</button>`;row.querySelector("button").addEventListener("click",()=>{state.selected.delete(id);updateTray();render();showSelection()});els.selectionList.append(row)});els.selectionDialog.showModal()}
async function copySelection(){const text="【希望衣装】\n"+selectedItems().map((item,i)=>`${field(item,["ID"])||i+1}｜${itemName(item)}｜${field(item,["カテゴリ"])}｜${field(item,["色"])}`).join("\n");try{await navigator.clipboard.writeText(text);els.copyMessage.textContent="コピーしました。"}catch{els.copyMessage.textContent="コピーできませんでした。"}}

[els.search,els.category,els.color,els.sleeve,els.pattern].forEach(x=>x.addEventListener("input",applyFilters));
els.reset.addEventListener("click",()=>{els.search.value="";els.category.value="";els.color.value="";els.sleeve.value="";els.pattern.value="";applyFilters()});
document.querySelectorAll(".dialog__close").forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));
els.viewSelection.addEventListener("click",showSelection);els.copy.addEventListener("click",copySelection);els.clear.addEventListener("click",()=>{state.selected.clear();updateTray();render();els.selectionDialog.close()});

fetch(API_URL).then(r=>r.json()).then(data=>{state.items=data.filter(item=>Object.values(item).some(v=>String(v??"").trim()!==""));setupFilters();applyFilters()}).catch(()=>{els.status.textContent="衣装データを読み込めませんでした。";els.count.textContent="0 ITEMS"});
